### ISSUE TITLE
pytest-timeout's tests fail on pypy3 Windows

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-timeout#46]
From https://github.com/pytest-dev/pytest-timeout/pull/45:

```
2019-11-20T10:47:29.4376002Z GLOB sdist-make: D:\a\pytest-timeout\pytest-timeout\setup.py
2019-11-20T10:47:31.0354032Z pypy3 create: D:\a\pytest-timeout\pytest-timeout\.tox\pypy3
2019-11-20T10:47:50.7392632Z pypy3 installdeps: pytest, pexpect
2019-11-20T10:47:59.3280264Z pypy3 inst: D:\a\pytest-timeout\pytest-timeout\.tox\.tmp\package\1\pytest-timeout-1.3.3.zip
2019-11-20T10:48:05.7915309Z pypy3 installed: atomicwrites==1.3.0,attrs==19.3.0,cffi==1.12.0,colorama==0.4.1,greenlet==0.4.13,importlib-metadata==0.23,more-itertools==7.2.0,packaging==19.2,pathlib2==2.3.5,pexpect==4.7.0,pluggy==0.13.0,ptyprocess==0.6.0,py==1.8.0,pyparsing==2.4.5,pytest==5.3.0,pytest-timeout==1.3.3,readline==6.2.4.1,six==1.13.0,wcwidth==0.1.7,zipp==0.6.0
2019-11-20T10:48:05.7925096Z pypy3 run-test-pre: PYTHONHASHSEED='281'
2019-11-20T10:48:05.7928537Z pypy3 run-test: commands[0] | py.test
2019-11-20T10:48:07.3011721Z INTERNALERROR> Traceback (most recent call last):
2019-11-20T10:48:07.3012233Z INTERNALERROR>   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\_pytest\main.py", line 192, in wrap_session
2019-11-20T10:48:07.3012455Z INTERNALERROR>     config._do_configure()
2019-11-20T10:48:07.3012747Z INTERNALERROR>   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\_pytest\config\__init__.py", line 726, in _do_configure
2019-11-20T10:48:07.3012939Z INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
2019-11-20T10:48:07.3013133Z INTERNALERROR>   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\pluggy\hooks.py", line 308, in call_historic
2019-11-20T10:48:07.3013359Z INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
2019-11-20T10:48:07.3013543Z INTERNALERROR>   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\pluggy\manager.py", line 92, in _hookexec
2019-11-20T10:48:07.3013723Z INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
2019-11-20T10:48:07.3014005Z INTERNALERROR>   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\pluggy\manager.py", line 86, in <lambda>
2019-11-20T10:48:07.3014196Z INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
2019-11-20T10:48:07.3014387Z INTERNALERROR>   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\pluggy\callers.py", line 208, in _multicall
2019-11-20T10:48:07.3014586Z INTERNALERROR>     return outcome.get_result()
2019-11-20T10:48:07.3014746Z INTERNALERROR>   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\pluggy\callers.py", line 80, in get_result
2019-11-20T10:48:07.3014928Z INTERNALERROR>     raise ex[1].with_traceback(ex[2])
2019-11-20T10:48:07.3015317Z INTERNALERROR>   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\pluggy\callers.py", line 187, in _multicall
2019-11-20T10:48:07.3015494Z INTERNALERROR>     res = hook_impl.function(*args)
2019-11-20T10:48:07.3015679Z INTERNALERROR>   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\_pytest\faulthandler.py", line 21, in pytest_configure
2019-11-20T10:48:07.3015879Z INTERNALERROR>     if faulthandler.is_enabled():
2019-11-20T10:48:07.3016034Z INTERNALERROR> AttributeError: module 'faulthandler' has no attribute 'is_enabled'
2019-11-20T10:48:07.3048062Z Traceback (most recent call last):
2019-11-20T10:48:07.3050004Z   File "c:\hostedtoolcache\windows\pypy\3.5.3\x86\lib-python\3\runpy.py", line 193, in _run_module_as_main
2019-11-20T10:48:07.3050379Z     "__main__", mod_spec)
2019-11-20T10:48:07.3050646Z   File "c:\hostedtoolcache\windows\pypy\3.5.3\x86\lib-python\3\runpy.py", line 85, in _run_code
2019-11-20T10:48:07.3052110Z     exec(code, run_globals)
2019-11-20T10:48:07.3052656Z   File "D:\a\pytest-timeout\pytest-timeout\.tox\pypy3\bin\py.test.EXE\__main__.py", line 7, in <module>
2019-11-20T10:48:07.3053586Z     sys.exit(main())
2019-11-20T10:48:07.3054237Z   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\_pytest\config\__init__.py", line 92, in main
2019-11-20T10:48:07.3054452Z     config=config
2019-11-20T10:48:07.3054710Z   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\pluggy\hooks.py", line 286, in __call__
2019-11-20T10:48:07.3054892Z     return self._hookexec(self, self.get_hookimpls(), kwargs)
2019-11-20T10:48:07.3055118Z   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\pluggy\manager.py", line 92, in _hookexec
2019-11-20T10:48:07.3055337Z     return self._inner_hookexec(hook, methods, kwargs)
2019-11-20T10:48:07.3057362Z   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\pluggy\manager.py", line 86, in <lambda>
2019-11-20T10:48:07.3057656Z     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
2019-11-20T10:48:07.3057957Z   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\pluggy\callers.py", line 208, in _multicall
2019-11-20T10:48:07.3058200Z     return outcome.get_result()
2019-11-20T10:48:07.3058480Z   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\pluggy\callers.py", line 80, in get_result
2019-11-20T10:48:07.3058719Z     raise ex[1].with_traceback(ex[2])
2019-11-20T10:48:07.3058995Z   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\pluggy\callers.py", line 187, in _multicall
2019-11-20T10:48:07.3059234Z     res = hook_impl.function(*args)
2019-11-20T10:48:07.3060361Z   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\_pytest\main.py", line 233, in pytest_cmdline_main
2019-11-20T10:48:07.3061092Z     return wrap_session(config, _main)
2019-11-20T10:48:07.3062439Z   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\_pytest\main.py", line 228, in wrap_session
2019-11-20T10:48:07.3062687Z     config._ensure_unconfigure()
2019-11-20T10:48:07.3062920Z   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\_pytest\config\__init__.py", line 731, in _ensure_unconfigure
2019-11-20T10:48:07.3063090Z     self.hook.pytest_unconfigure(config=self)
2019-11-20T10:48:07.3063295Z   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\pluggy\hooks.py", line 286, in __call__
2019-11-20T10:48:07.3063480Z     return self._hookexec(self, self.get_hookimpls(), kwargs)
2019-11-20T10:48:07.3063687Z   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\pluggy\manager.py", line 92, in _hookexec
2019-11-20T10:48:07.3063867Z     return self._inner_hookexec(hook, methods, kwargs)
2019-11-20T10:48:07.3064072Z   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\pluggy\manager.py", line 86, in <lambda>
2019-11-20T10:48:07.3064260Z     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
2019-11-20T10:48:07.3064631Z   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\pluggy\callers.py", line 208, in _multicall
2019-11-20T10:48:07.3064793Z     return outcome.get_result()
2019-11-20T10:48:07.3065038Z   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\pluggy\callers.py", line 80, in get_result
2019-11-20T10:48:07.3065277Z     raise ex[1].with_traceback(ex[2])
2019-11-20T10:48:07.3065488Z   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\pluggy\callers.py", line 187, in _multicall
2019-11-20T10:48:07.3065641Z     res = hook_impl.function(*args)
2019-11-20T10:48:07.3065856Z   File "d:\a\pytest-timeout\pytest-timeout\.tox\pypy3\site-packages\_pytest\faulthandler.py", line 42, in pytest_unconfigure
```

**Comment by nicoddemus** [comment]
pypy3 has been removed from the build matrix for now in d39bec1.

**Comment by flub** [comment]
too old, though there still seem to be windows failures in ci.
