### ISSUE TITLE
UnicodeEncodeError when printing standard output

### ISSUE THREAD

**Issue by pytest-timeout-bot** [pytest-dev/pytest-timeout#7]
**[Original report](https://bitbucket.org/pytest-dev/pytest-timeout/issue/7) by Bruno Oliveira (Bitbucket: [nicoddemus](https://bitbucket.org/nicoddemus), GitHub: [nicoddemus](https://github.com/nicoddemus)).**

----------------------------------------

Hi Floris,

When a test timeouts, it may fail to print the captured standard output if the output contains non-ascii characters:

```python
# encoding: UTF-8
import time
import pytest

@pytest.mark.timeout(1)
def test_foo():    
    print '¯\_(ツ)_/¯'
    time.sleep(2)
```

Executing this test, it gives this error:

```
============================= test session starts =============================
platform win32 -- Python 2.7.7 -- py-1.4.26 -- pytest-2.6.4
plugins: timeout, localserver, xdist, cov, mock
collected 1 items

test_foo.py
+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Captured stdout ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "D:\Shared\dist\12.0-all\pytest_timeout-0.3\lib\site-packages\pytest_timeout.py", line 251, in timeout_timer
    write(stdout)
  File "D:\Shared\dist\12.0-all\pytest_timeout-0.3\lib\site-packages\pytest_timeout.py", line 304, in write
    stream.write(text)
  File "D:\Shared\dist\12.0-win64\python-2.7.X\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\xaf' in position 0: character maps to <undefined>
```

This happens in version `0.3` and `0.5`.

**Comment by flub** [comment]
No one's complained about this for many years.  Closing for now, but feel free to open new concrete issues.
